### ISSUE TITLE
Mention version in Readme

### ISSUE THREAD

**Issue by danielfett** [chike0905/sd-jwt-ts#1]
Thanks for providing this! Always good to see a spec actually implemented.

Since the SD-JWT spec is under development, I think it would be helpful to mention the version that you have implemented. The IETF draft version numbers would be helpful or the date/commit as Christian did in his readme: https://github.com/christianpaquin/sd-jwt

Thanks!

**Comment by chike0905** [comment]
Thank you for your comment!

I added the I-D version number.
